import {MigrationInterface, QueryRunner} from "typeorm";

export class Initial1609705376527 implements MigrationInterface {
    name = 'Initial1609705376527'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "address" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "address_line_1" character varying NOT NULL, "address_line_2" character varying, "postal_code" character varying NOT NULL, "city" character varying NOT NULL, "state" character varying NOT NULL, "country" character varying NOT NULL, "latitude" double precision, "longitute" double precision, CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "admin_setting" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "admin_key" character varying NOT NULL, "value" character varying NOT NULL, CONSTRAINT "PK_c1b47d26727de2c13b3d9ef2115" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "authority" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "name" character varying NOT NULL, CONSTRAINT "UQ_6bd550a01abba64a7a256511dda" UNIQUE ("name"), CONSTRAINT "PK_b0f9bb35ff132fc6bd92d0582ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "name" character varying NOT NULL, CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contact_us" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "name" character varying NOT NULL, "email" character varying NOT NULL, "description" character varying NOT NULL, CONSTRAINT "PK_b61766a4d93470109266b976cfe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "industry" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "name" character varying NOT NULL, CONSTRAINT "PK_fc3e38485cff79e9fbba8f13831" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mobile_setting" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "email" boolean NOT NULL, "push_notification" boolean NOT NULL, "time" boolean NOT NULL, "linkedEntities" json NOT NULL, CONSTRAINT "PK_192b60c149f62ca94aa243542d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "device_type" character varying NOT NULL, "token" character varying NOT NULL, "title" character varying NOT NULL, "message" character varying NOT NULL, "linkedEntities" json NOT NULL, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "q_branch_admin" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "linkedEntities" json NOT NULL, CONSTRAINT "PK_819370a4c6813852bff67a0831a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "q_branch_time_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "start_time" date NOT NULL, "end_time" date NOT NULL, "date" date NOT NULL, CONSTRAINT "PK_8a9e4dcf91dd926542cf4c5abd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "q_branch" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "branch_name" character varying NOT NULL, "image_url" character varying, "about" character varying, "phone" character varying NOT NULL, "open_time" character varying NOT NULL, "close_time" character varying NOT NULL, "linkedEntities" json NOT NULL, CONSTRAINT "PK_d7b4a4cd69a09c5282569fd190c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "q_partner_admin" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "linkedEntities" json NOT NULL, CONSTRAINT "PK_aca531f0dd4d397a89742ba48eb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "q_partner" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "email" character varying NOT NULL, "name" character varying NOT NULL, "image_url" character varying, "cover_image_url" character varying, "offer" character varying, "about" character varying NOT NULL, "number_of_branch" character varying NOT NULL, "number_of_branch_admin" character varying NOT NULL, "linkedEntities" json NOT NULL, CONSTRAINT "PK_c589b279ff462c9441b969c3d9a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "q_user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "phone" character varying NOT NULL, "gender" character varying, "login_type" character varying, "social_media_type" character varying, "social_media_id" character varying, "linkedEntities" json NOT NULL, CONSTRAINT "PK_fb6c8bef67624d1afc0cc58a0bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "queue" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "amount" numeric(10,2) NOT NULL, "transaction_number" character varying NOT NULL, "transaction_desc" character varying NOT NULL, "transaction_date" date NOT NULL, "queue_number" integer, "timezone" date, "estimated_time" integer, "is_completed" boolean NOT NULL DEFAULT false, "comment" character varying, "min_notification_sent" boolean NOT NULL DEFAULT false, "linkedEntities" json NOT NULL, CONSTRAINT "PK_4adefbd9c73b3f9a49985a5529f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "smartq_platform_setting" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "name" character varying NOT NULL, "q_transactionamount" numeric(10,2) NOT NULL, "description" character varying NOT NULL, "adroidversion" double precision NOT NULL, "iosversion" double precision NOT NULL, "email" character varying NOT NULL, CONSTRAINT "PK_0d3878c790aeea053a35c2e287c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "terms_conditions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "content" character varying NOT NULL, CONSTRAINT "PK_8646783cf3677db5157b4a1af76" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transaction_status" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "name" character varying NOT NULL, CONSTRAINT "PK_05fbbdf6bc1db819f47975c8c0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transaction_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "name" character varying NOT NULL, "time" integer NOT NULL, "linkedEntities" json NOT NULL, CONSTRAINT "PK_e4e15bcea926d360cfeea703c36" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_device" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "device_token" character varying NOT NULL, "device_type" character varying NOT NULL, "os_version" character varying NOT NULL, "force_update" boolean NOT NULL DEFAULT false, "linkedEntities" json NOT NULL, CONSTRAINT "PK_0232591a0b48e1eb92f3ec5d0d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "createdDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedBy" character varying, "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "active" boolean NOT NULL DEFAULT true, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "activated" boolean, "langKey" character varying, "phone" character varying, "linkedEntities" json NOT NULL, "metaData" json, "imageUrl" character varying, "activationKey" character varying, "resetKey" character varying, "resetDate" TIMESTAMP, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "user_device"`);
        await queryRunner.query(`DROP TABLE "transaction_type"`);
        await queryRunner.query(`DROP TABLE "transaction_status"`);
        await queryRunner.query(`DROP TABLE "terms_conditions"`);
        await queryRunner.query(`DROP TABLE "smartq_platform_setting"`);
        await queryRunner.query(`DROP TABLE "queue"`);
        await queryRunner.query(`DROP TABLE "q_user"`);
        await queryRunner.query(`DROP TABLE "q_partner"`);
        await queryRunner.query(`DROP TABLE "q_partner_admin"`);
        await queryRunner.query(`DROP TABLE "q_branch"`);
        await queryRunner.query(`DROP TABLE "q_branch_time_log"`);
        await queryRunner.query(`DROP TABLE "q_branch_admin"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TABLE "mobile_setting"`);
        await queryRunner.query(`DROP TABLE "industry"`);
        await queryRunner.query(`DROP TABLE "contact_us"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP TABLE "authority"`);
        await queryRunner.query(`DROP TABLE "admin_setting"`);
        await queryRunner.query(`DROP TABLE "address"`);
    }

}
